config/routes.rb
Rails.application.routes.draw do
  resources :votes

  resources :voters

  resources :canidates

  namespace :api do
    namespace :v1 do
      resources :canidates
      resources :voters
      resources :votes
    end
  end

end

app/models/canidate.rb
class Canidate < ActiveRecord::Base
end

app/models/vote.rb
class Vote < ActiveRecord::Base
end

app/models/voter.rb
require 'securerandom'

class Voter < ActiveRecord::Base
  before_save :add_token

  def as_json(options)
    hash = {id: id,
            name: name,
            party: party}
    if options[:include_token]
      hash.merge!(token: token)
    end

    {person: hash}
  end

  private

  def add_token
    self.token ||= SecureRandom.uuid
  end

end

app/controllers/api/v1/canidates_controller.rb
class API::V1::CanidatesController < ActionController::API
  before_filter :load_user, only: [:show]

  def index
    @canidates = Canidate.all
    render json: @canidates
  end

  def show
    render json: @canidate
  end

  private

  def load_user
    @canidate = Canidate.find(params[:id])
  end

end

app/controllers/api/v1/voters_controller.rb
class API::V1::VotersController < ActionController::API
  include ActionController::HttpAuthentication::Token::ControllerMethods
  before_filter :load_voter, only: [:show]
  before_filter :restrict_access_to_voter, only: [:show]


  def create
    @voter = Voter.new(voter_params)
    if @voter.save
      render json: @voter.as_json(include_token: true), status: :created, location: api_v1_voter_path(@voter)
    else
      render json: {errors: @voter.errors}, status: :bad_request
    end
  end

  def show
    render json: @voter
  end

  private

  def load_voter
    @voter = Voter.find(params[:id])
  end

  def restrict_access_to_voter
    # HEADER AUTHENTICATION
    # authenticate_or_request_with_http_token do |token, options|
    #   @person.token == token
    # end

    unless @voter.token == params[:token]
      render nothing: true, status: :unauthorized
    end
  end

  def voter_params
    params.require(:voter).permit(:name, :party)
  end

end

app/controllers/api/v1/votes_controller.rb
class API::V1::VotesController < ActionController::API
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/canidates_controller.rb
class CanidatesController < ApplicationController::API
  before_action :set_canidate, only: [:show, :edit, :update, :destroy]

  # GET /canidates
  # GET /canidates.json
  def index
    @canidates = Canidate.all
  end

  # GET /canidates/1
  # GET /canidates/1.json
  def show
  end

  # GET /canidates/new
  def new
    @canidate = Canidate.new
  end

  # GET /canidates/1/edit
  def edit
  end

  # POST /canidates
  # POST /canidates.json
  def create
    @canidate = Canidate.new(canidate_params)

    respond_to do |format|
      if @canidate.save
        format.html { redirect_to @canidate, notice: 'Canidate was successfully created.' }
        format.json { render :show, status: :created, location: @canidate }
      else
        format.html { render :new }
        format.json { render json: @canidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /canidates/1
  # PATCH/PUT /canidates/1.json
  def update
    respond_to do |format|
      if @canidate.update(canidate_params)
        format.html { redirect_to @canidate, notice: 'Canidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @canidate }
      else
        format.html { render :edit }
        format.json { render json: @canidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /canidates/1
  # DELETE /canidates/1.json
  def destroy
    @canidate.destroy
    respond_to do |format|
      format.html { redirect_to canidates_url, notice: 'Canidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_canidate
      @canidate = Canidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def canidate_params
      params.require(:canidate).permit(:name, :party)
    end
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController::API
  before_action :set_voter, only: [:show, :edit, :update, :destroy]

  # GET /voters
  # GET /voters.json
  def index
    @voters = Voter.all
  end

  # GET /voters/1
  # GET /voters/1.json
  def show
  end

  # GET /voters/new
  def new
    @voter = Voter.new
  end

  # GET /voters/1/edit
  def edit
  end

  # POST /voters
  # POST /voters.json
  def create
    @voter = Voter.new(voter_params)

    respond_to do |format|
      if @voter.save
        format.html { redirect_to @voter, notice: 'Voter was successfully created.' }
        format.json { render :show, status: :created, location: @voter }
      else
        format.html { render :new }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voters/1
  # PATCH/PUT /voters/1.json
  def update
    respond_to do |format|
      if @voter.update(voter_params)
        format.html { redirect_to @voter, notice: 'Voter was successfully updated.' }
        format.json { render :show, status: :ok, location: @voter }
      else
        format.html { render :edit }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voters/1
  # DELETE /voters/1.json
  def destroy
    @voter.destroy
    respond_to do |format|
      format.html { redirect_to voters_url, notice: 'Voter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voter
      @voter = Voter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voter_params
      params.require(:voter).permit(:name, :party)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController::API
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:voter_id, :canidate_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/canidates_helper.rb
module CanidatesHelper
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/canidates/_form.html.erb
<%= form_for(@canidate) do |f| %>
  <% if @canidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@canidate.errors.count, "error") %> prohibited this canidate from being saved:</h2>

      <ul>
      <% @canidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :party %><br>
    <%= f.text_field :party %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/canidates/edit.html.erb
<h1>Editing canidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @canidate %> |
<%= link_to 'Back', canidates_path %>

app/views/canidates/index.html.erb
<h1>Listing canidates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Party</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @canidates.each do |canidate| %>
      <tr>
        <td><%= canidate.name %></td>
        <td><%= canidate.party %></td>
        <td><%= link_to 'Show', canidate %></td>
        <td><%= link_to 'Edit', edit_canidate_path(canidate) %></td>
        <td><%= link_to 'Destroy', canidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Canidate', new_canidate_path %>

app/views/canidates/new.html.erb
<h1>New canidate</h1>

<%= render 'form' %>

<%= link_to 'Back', canidates_path %>

app/views/canidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @canidate.name %>
</p>

<p>
  <strong>Party:</strong>
  <%= @canidate.party %>
</p>

<%= link_to 'Edit', edit_canidate_path(@canidate) %> |
<%= link_to 'Back', canidates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BallotBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/voters/_form.html.erb
<%= form_for(@voter) do |f| %>
  <% if @voter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voter.errors.count, "error") %> prohibited this voter from being saved:</h2>

      <ul>
      <% @voter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :party %><br>
    <%= f.text_field :party %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/voters/edit.html.erb
<h1>Editing voter</h1>

<%= render 'form' %>

<%= link_to 'Show', @voter %> |
<%= link_to 'Back', voters_path %>

app/views/voters/index.html.erb
<h1>Listing voters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Party</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voters.each do |voter| %>
      <tr>
        <td><%= voter.name %></td>
        <td><%= voter.party %></td>
        <td><%= link_to 'Show', voter %></td>
        <td><%= link_to 'Edit', edit_voter_path(voter) %></td>
        <td><%= link_to 'Destroy', voter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voter', new_voter_path %>

app/views/voters/new.html.erb
<h1>New voter</h1>

<%= render 'form' %>

<%= link_to 'Back', voters_path %>

app/views/voters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @voter.name %>
</p>

<p>
  <strong>Party:</strong>
  <%= @voter.party %>
</p>

<%= link_to 'Edit', edit_voter_path(@voter) %> |
<%= link_to 'Back', voters_path %>

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :voter_id %><br>
    <%= f.number_field :voter_id %>
  </div>
  <div class="field">
    <%= f.label :canidate_id %><br>
    <%= f.number_field :canidate_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <thead>
    <tr>
      <th>Voter</th>
      <th>Canidate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.voter_id %></td>
        <td><%= vote.canidate_id %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Voter:</strong>
  <%= @vote.voter_id %>
</p>

<p>
  <strong>Canidate:</strong>
  <%= @vote.canidate_id %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>